CXX      := c++
CXXFLAGS := -Wall -Wextra -Werror -std=c++98 -Iinclude
TARGET   := Bureaucrat
SRCS     := main.cpp \
			Bureaucrat.cpp \

OBJS     := $(SRCS:.cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $^ -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(TARGET)

re: fclean all

.PHONY: all clean